[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "contribution"
description = "Awesome Movie Database Contribution Service"
version = "0.1.0"
license = { file = "LICENSE" }
requires-python = ">=3.12.3"

dependencies = [
    "uuid7==0.1.*",
    "aio-pika==9.4.*",
    "dishka==1.1.*",
    "motor==3.4.*",
    "aioboto3==13.0.*",
    "types-aioboto3[aioboto3,s3]",
    "cyclopts==2.7.*",
    "adaptix==3.0.0b7",
    "redis==5.0.*",
]

[project.optional-dependencies]
test = [
    "pytest==8.2.*",
    "pytest-asyncio==0.23.*",
]
dev = [
    "mypy==1.8.*",
    "ruff==0.1.*",
    "pre-commit==3.5.*",
]
web_api = [
    "fastapi==0.111.*",
    "uvicorn==0.29.*",
]
event_consumer = [
    "faststream==0.5.*",
]
