[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "contribution"
description = "Awesome Movie Database Contribution Service"
version = "0.1.0"
license = { file = "LICENSE" }
requires-python = ">=3.12.3"

dependencies = [
    "uuid7==0.1.*",
    "aio-pika==9.4.*",
    "dishka==1.3.*",
    "motor==3.5.*",
    "cyclopts==2.9.*",
    "adaptix==3.0.0b7",
    "redis==5.0.*",
]

[project.optional-dependencies]
test = [
    "pytest==8.3.*",
    "pytest-asyncio==0.23.*",
]
dev = [
    "mypy==1.11.*",
    "ruff==0.6.*",
    "pre-commit==3.8.*",
]
web_api = [
    "fastapi==0.112.*",
    "uvicorn[standart]==0.30.*",
    "gunicorn==23.0.*",
]
event_consumer = [
    "faststream==0.5.*",
]
tui = [
    "textual==0.72.*",
]

[project.scripts]
contribution = "contribution.main.cli:main"
