[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "contribution"
description = "Awesome Movie Database Contribution Service"
version = "0.1.0"
license = { file = "LICENSE" }
requires-python = "==3.10.*"

dependencies = [
    "uuid7==0.1.*",
    "aio-pika==9.4.*",
    "dishka==1.1.*",
    "fastapi==0.111.*",
    "uvicorn==0.29.*",
]

[project.optional-dependencies]
dev = [
    "mypy==1.8.*",
    "ruff==0.1.*",
    "pre-commit==3.5.*",
]
