server:
  http_listen_port: 9080
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://contribution.loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/contribution/error.log
