server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://contribution.loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: contribution
    static_configs:
      - targets:
          - localhost
        labels:
          job: contribution
          __path__: /var/lib/docker/containers/*/*.log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
      - json:
          source: attrs
          expressions:
            tag: tag
      - drop:
          source: stream
          expression: 'stderr'
      - match:
          selector: '{tag=~""} != "contribution.web_api"'
          action: drop
      - output:
          source: log
